# Generated by Django 4.2.5 on 2024-01-28 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_size_quantity'),
        ('core', '0003_cartitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.size'),
        ),
    ]
