# Generated by Django 4.2.5 on 2024-01-31 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cartitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_ordered',
        ),
    ]
