# Generated by Django 4.2.5 on 2024-02-06 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_product_created_at'),
        ('core', '0007_order_is_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.productsize'),
        ),
    ]
