# Generated by Django 4.2.5 on 2024-01-25 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_productoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='days_difference',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='expiry_date',
        ),
    ]
