# Generated by Django 4.2.5 on 2024-01-29 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_size_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='quantity',
        ),
    ]
